In [ ]:
# mempersiapkan library
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, Activation, Dropout
from tensorflow.keras.layers import Conv1D, MaxPooling1D, GlobalMaxPooling1D
import numpy as np  #digunakan untuk perhitugan numerik
import pandas as pd #import pandas untuk membaca file csv
from sklearn.model_selection import train_test_split #untuk memecah data training dan test

In [ ]:
df = pd.read_csv('/content/tweetalay.csv')
df.head()

sentimen                                              Tweet
0         2  lagu bosan apa yang aku save ni huhuhuhuhuhuhu...
1         2  kita lanjutkan saja diam ini hingga kau dan ak...
2         1  doa rezeki tak putus inna haa zaa larizquna ma...
3         1  makasih loh ntar kita bagi hasil aku 99 9 sisa...
4         2  aku tak faham betul jenis orang malaysia yang ...

MEMBUAT DATASET UNTUK TRAINING NYA

In [ ]:
# mengambil bagian text tweet dan menghitung jumlah textnya (variabel x / varibel input)
text = df["Tweet"].tolist()
print(len(text))

10806


In [ ]:
# membuat variabel y atau target atau sentimen
y = df["sentimen"]
y = to_categorical(y) #y ubah ke kategorical
print(y)

[[0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 ...
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


In [ ]:
# melihat nilai pada setiap jenis data, 0 = netral, 2 = negatif, 1 = positif
df["sentimen"].value_counts()

0    5327
2    2887
1    2592
Name: sentimen, dtype: int64

In [ ]:
# men-tokenize text twitter
token = Tokenizer()
token.fit_on_texts(text)

In [ ]:
# membuat index dari kata-kata
token.index_word

{1: 'aku',
 2: 'kamu',
 3: 'yang',
 4: 'dan',
 5: 'kita',
 6: 'yg',
 7: 'di',
 8: 'ada',
 9: 'tak',
 10: 'ini',
 11: 'apa',
 12: 'orang',
 13: 'dia',
 14: 'ni',
 15: 'ya',
 16: 'itu',
 17: 'tapi',
 18: 'nak',
 19: 'mereka',
 20: 'ke',
 21: 'untuk',
 22: 'mau',
 23: 'kalau',
 24: 'juga',
 25: 'bisa',
 26: 'dari',
 27: 'dengan',
 28: 'jadi',
 29: 'lagi',
 30: 'kau',
 31: 'buat',
 32: 'sama',
 33: 'tu',
 34: 'aja',
 35: 'ga',
 36: 'akan',
 37: 'tidak',
 38: 'dah',
 39: 'jangan',
 40: 'kalo',
 41: 'gak',
 42: 'hari',
 43: 'bukan',
 44: 'dalam',
 45: 'je',
 46: 'boleh',
 47: 'semua',
 48: 'pernah',
 49: 'masih',
 50: 'suka',
 51: 'kan',
 52: 'karena',
 53: 'pun',
 54: 'baik',
 55: 'lebih',
 56: 'tau',
 57: 'allah',
 58: 'mana',
 59: 'saya',
 60: 'baru',
 61: 'bila',
 62: 'lah',
 63: 'adalah',
 64: 'banyak',
 65: 'lain',
 66: 'nanti',
 67: 'nya',
 68: 'la',
 69: 'dulu',
 70: 'harus',
 71: 'udah',
 72: 'hati',
 73: 'sudah',
 74: 'punya',
 75: 'jika',
 76: 'batik',
 77: 'pada',
 78: 'macam',
 

In [ ]:
# menghitung jumlah kata 
vocab = len(token.index_word)+1
vocab

22707

In [ ]:
# merubah setiap kalimat menjadi bentuk sequential dari bentuk index tokennya contoh nya seperti ini
# aku = index 1, lagi = index 29, galau = index 2699, nih = index 122
x =['aku lagi galau nih'] 
token.texts_to_sequences(x)

[[1, 29, 2699, 122]]

In [ ]:
# membuat seluruh kalimatnya menjadi bentuk index seperti di atas
encode_text = token.texts_to_sequences(text)
print(encode_text)

[[434, 1051, 11, 3, 1, 1743, 14, 9682], [5, 4557, 110, 318, 10, 660, 30, 4, 1, 2611, 37, 47, 3036, 70, 9683, 72], [291, 538, 9, 632, 2612, 999, 3656, 3657, 2613, 3658, 759, 779, 3659, 10, 1000, 2314, 132, 158, 2, 301], [704, 485, 399, 5, 82, 571, 1, 4558, 705, 3660, 31, 2], [1, 9, 410, 185, 351, 12, 383, 3, 9, 877, 18, 2614, 156, 2315, 33, 1, 1499, 337, 18, 1162], [1888, 174, 780, 7, 845, 1889, 1617, 6245, 6246, 510, 2, 25, 3661], [279, 13, 78, 14, 2065, 14, 2066, 1, 572, 358, 154, 4559, 2067, 476, 17, 42, 14, 1, 127, 251, 13, 4560, 1, 301], [15, 1, 36, 147, 83, 1744, 43, 2068, 83, 633, 83, 1744], [1, 34, 1163, 32, 1001, 100, 689, 2, 195, 15, 292], [1, 435, 18, 2069, 1317, 179, 1234, 17, 115, 1, 706, 99, 1, 351, 465, 963, 4, 465, 2316], [1164, 16, 707, 964, 3662, 32, 4561, 4562, 4563, 15, 1745, 1, 119, 87, 1318, 525, 4564, 193, 4565, 6, 808, 166, 4566, 4567], [141, 613, 690, 1, 49, 614, 257, 2615, 1399, 7, 2317], [1, 367, 6247, 3663, 3664], [43, 1500, 155, 615, 285, 3665, 3666, 9684, 1

In [ ]:
# menormalisasikan kalimat karena jumlah kata tiap kalimat berbeda maka akan kita ubah menjadi lebih fit, kalau lebih akan dipotong, kalau kurang akan dikasih padding/spasi
max_kata = 100 #panjang maximal kalimat adalah 100
X = pad_sequences(encode_text, maxlen = max_kata, padding="post" ) #jika post diganti "pre" maka 0 nya akan di depan
X

array([[  434,  1051,    11, ...,     0,     0,     0],
       [    5,  4557,   110, ...,     0,     0,     0],
       [  291,   538,     9, ...,     0,     0,     0],
       ...,
       [  325,     6,   317, ...,     0,     0,     0],
       [  126,   222,    21, ...,     0,     0,     0],
       [  140,    57, 22706, ...,     0,     0,     0]], dtype=int32)

In [ ]:
# memotong data menggunakan fungsi dari sklearn diatas
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=40, test_size=0.3, stratify=y)

In [ ]:
# mengubah kedalam bentuk array numpy
X_train = np.asarray(X_train)
X_test = np.asarray(X_test)
y_train = np.asarray(y_train)
y_test = np.asarray(y_test)

MEMBUAT MODEL TRAINING NYA

In [ ]:
# menentukan vektor size untuk besar size saat proses embedding, jadi sequence huruf yang merupakan hasil konversi dari kata akan kita ubah menjadi word embedding
# Secara sederhana, word embedding adalah proses konversi sebuat teks menjadi angka.
vec_size = 300 
model = Sequential()
# tambahkan 1 layer untuk mengubah sequance index kata menjadi vektor sebanyak Vocab yang diatas, lalu output sebesar vektor_size, lalu inputnya sebanyak maximal 100 kata
model.add(Embedding(vocab, vec_size, input_length= max_kata))
# Menggunakan Convolutional Neural Networks 1 Dimensi sebanyak filter 64 dan 8 unit Convolution kemudian maxpooling
model.add(Conv1D(64,8, activation="relu"))
model.add(MaxPooling1D(2))
# dropout adalah bentuk configurasi agar tidak overfitting.
model.add(Dropout(0.5))

model.add(Dense(32, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(16, activation='relu'))
model.add(GlobalMaxPooling1D())
# membuat layer klasifikasi akhir
model.add(Dense(3, activation='softmax'))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 100, 300)          6812100   
                                                                 
 conv1d (Conv1D)             (None, 93, 64)            153664    
                                                                 
 max_pooling1d (MaxPooling1D  (None, 46, 64)           0         
 )                                                               
                                                                 
 dropout (Dropout)           (None, 46, 64)            0         
                                                                 
 dense (Dense)               (None, 46, 32)            2080      
                                                                 
 dropout_1 (Dropout)         (None, 46, 32)            0         
                                                        

In [ ]:
# membuat compile
model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=['accuracy'])

In [ ]:
# training
model.fit(X_train, y_train, epochs=100, validation_data =(X_test, y_test))

Epoch 1/100
237/237 [==============================] - 40s 168ms/step - loss: 1.0475 - accuracy: 0.4934 - val_loss: 1.0495 - val_accuracy: 0.4963
Epoch 2/100
237/237 [==============================] - 40s 167ms/step - loss: 0.9897 - accuracy: 0.5234 - val_loss: 0.9884 - val_accuracy: 0.5358
Epoch 3/100
237/237 [==============================] - 40s 167ms/step - loss: 0.7663 - accuracy: 0.6650 - val_loss: 0.9287 - val_accuracy: 0.5734
Epoch 4/100
237/237 [==============================] - 40s 168ms/step - loss: 0.4936 - accuracy: 0.8124 - val_loss: 0.9607 - val_accuracy: 0.5725
Epoch 5/100
237/237 [==============================] - 39s 166ms/step - loss: 0.3141 - accuracy: 0.8973 - val_loss: 1.0326 - val_accuracy: 0.5663
Epoch 6/100
237/237 [==============================] - 39s 166ms/step - loss: 0.2245 - accuracy: 0.9281 - val_loss: 1.1595 - val_accuracy: 0.5549
Epoch 7/100
237/237 [==============================] - 40s 167ms/step - loss: 0.1815 - accuracy: 0.9435 - val_loss: 1.1783 -

In [ ]:
# melakukan klasifikasi kalimat
def get_encode(x):
  x = token.texts_to_sequences(x)
  x = pad_sequences(x, maxlen = max_kata, padding="post")
  return x 

In [ ]:
# mencoba kalimat
x = ['setiap malem aku selalu sendiri']
x = get_encode(x)

In [ ]:
# mencoba melakukan prediksi
np.argmax(model.predict(x), axis=-1)

array([1])